### PR TITLE
Fix notification drop shadow

### PR DESCRIPTION
**Pull request by serebit**
## Description

Fixes a regression from #222 where the drop shadow on notification popups was cut off by the window border.

### Submitter Checklist

- [x] Squashed commits with `git rebase -i` (if needed)
- [x] Built budgie-desktop and verified that the patch worked (if needed)

### CODE REVIEW

**Review by EbonJaeger — COMMENTED** [review]
This does fix the issue, but I feel like the gap between notifications is now too large. Maybe worth playing with the spacing [here](https://github.com/BuddiesOfBudgie/budgie-desktop/blob/main/src/daemon/notifications/dbus.vala#L113) to see if it can be tightened up. inb4 it looks good as-is on high DPI :P

**Comment by serebit** [comment]
Shrank the top margin from 8 to 2, so the total is now 10, and set BUFFER_ZONE to 0. Shadow still fully appears.

**Review by EbonJaeger — APPROVED** [review]
Looks good to me! Thanks for fixing this!

**Review by JoshStrobl — APPROVED** [review]
LGTM, thanks!

**Pull request merged**
