### PR TITLE
Add preferred application styling with some logic

### PR DESCRIPTION
**Pull request by fossfreedom**
## Description
This adds the the GNOME 42 color-scheme support at a basic level.  It is intended to be the starter for 10 implementation to the larger discussion piece how to best handle libadwaita stuff.

A new drop down exists in budgie desktop-settings allowing a user to set the color-scheme styling preference.

Also some libhandy type logic has been added to set the color-scheme to dark if the chosen theme has the "-dark" name (and similar logic for light). This is the hard-coded libhandy "themes must end with -dark or -light".  Suggest future PRs will deal with additional logic if deemed necessary.

This removes the "dark-theme" switch toggle - doesnt make sense anymore - at least directly.  The dark-theme is now connected to the styling preference i.e. setting "preferred dark" will set the dark-theme gsettings value to its dark boolean value.

### Submitter Checklist

- [X] Squashed commits with `git rebase -i` (if needed)
- [X] Built budgie-desktop and verified that the patch worked (if needed)

### CODE REVIEW

**Comment by fossfreedom** [comment]
> I would recommend splitting the theme name by dashes, spaces, and underscores, then looking for the word "dark" in the array of words. Some themes don't end with "dark" - Matcha, for example, is named as `Matcha-{dark,light,}-<color>`.

fair enough. done.

**Comment by JoshStrobl** [comment]
> This removes the "dark-theme" switch toggle - doesnt make sense anymore - at least directly. The dark-theme is now connected to the styling preference i.e. setting "preferred dark" will set the dark-theme gsettings value to its dark boolean value.

I am not entirely sure I agree with that and it runs counter to the objectives of #27. Realistically we should swapping both the theme (e.g. Materia -> Materia-dark) and the "standard" preference. Otherwise we are trading one user complexity and inconsistency for another.

**Comment by EbonJaeger** [comment]
Is this pre-empted by https://github.com/BuddiesOfBudgie/budgie-desktop/pull/444?

**Comment by serebit** [comment]
Yeah, I think this has been effectively replaced by #444 and can probably be closed.

**Pull request closed without merging**
