### PR TITLE
Add support for mutter 10 / GNOME42

### PR DESCRIPTION
**Pull request by fossfreedom**
## Description
This add mutter 10 / GNOME 42 support.

This also tidies up and removed mutter 8 / GNOME 40 support

Marked as WIP.

### Submitter Checklist

- [ ] Squashed commits with `git rebase -i` (if needed)
- [ ] Built budgie-desktop and verified that the patch worked (if needed)

### CODE REVIEW

**Comment by rodrigofarias77** [comment]
Thank you! Fedora Rawhide is happy with this.

**Comment by fossfreedom** [comment]
@rodrigofarias77 thx.  Please do help out testing here - I know various bits like gsettings keys have been removed - so it would be more than helpful if you find any unexpected issues please let me know.

**Comment by JoshStrobl** [comment]
LGTM, feel free to mark as ready for review when you are comfortable getting it merged. Going to see what I can do to test under 42.x on Arch, or maybe through an Ubuntu Daily on a machine.

**Comment by fossfreedom** [comment]
I've tested this on debian sid + its experimental repo that has mutter-10 etc.

Seems to work here.  With the confirmation of working on rawhide, I suppose final confirmation with arch would be nice but I don't know if arch has all the necessary beta packages right at this moment.

**Pull request merged**
