### PR TITLE
fix: inability for popover pin button to be themed

### PR DESCRIPTION
**Pull request by JoshStrobl**
## Description
Fixes inability for popover pin button to be themed.

For reviewers: Only actual change in the SASS is the following code block. Rest I shall blame on format-on-save.

```
.icon-popover {
  .icon-popover-pin.alert {
    color: $alert_color;
  }
}
```

### CODE REVIEW

**Comment by JoshStrobl** [comment]
Ah true, sec

**Comment by JoshStrobl** [comment]
Fixed.

**Review by EbonJaeger — APPROVED** [review]
Awesome, LGTM!

**Review by serebit — APPROVED** [review]
LGTM!

**Pull request merged**
