### PR TITLE
Fix Current Internal Theme

### LINKED ISSUE #44: Fix Current Internal Theme
A precursor to #22.

Budgie v10.5.3's internal theme is a mess that's inconsistent across underlying GTK themes and just generally looks dated and unpolished, to such a degree that Solus actually hides the option to use the built-in theme. This issue tracks an effort to clean up the stylesheet in-place and bring it up to a reasonable standard before the full redesign in #22, along with making it consistent even when the underlying GTK theme is swapped out.

## Checklist

- [x] Panel
  - [x] Start Panel Region
  - [ ] Center Panel Region
  - [x] End Panel Region
  - [ ] Status Applet
  - [x] Icon Tasklist
  - [x] Clock Applet
  - [ ] Other Applets
  - [x] App Menu
- [x] Raven
  - [x] Raven Applets View
  - [x] Raven Notifications View
- [x] Notification Popups
- [ ] End Session Dialog
- [ ] Sound/Brightness OSD
- [ ] Polkit Dialog
- [ ] Run Dialog

### PR DESCRIPTION
**Pull request by serebit**
## Description

Will resolve #44.

Not every widget has been restyled - all popovers except the Budgie Menu have been left alone due to difficulty with styling.

### Checklist

- [x] Panel
  - [x] Center Panel Region
  - [x] Status Applet
  - [x] Other Applets
- [x] End Session Dialog
- [x] Sound/Brightness OSD
- [x] Polkit Dialog
- [x] Run Dialog

### CODE REVIEW

**Comment by Drsheppard01** [comment]
@serebit with great respect, I don't know if this can help but I used this https://github.com/vinceliuice/WhiteSur-gtk-theme/blob/master/src/sass/gtk/apps/_budgie.scss settings. This adds a distinctive border around the widgets and looks very aesthetically pleasing.

My screenshot:
https://pingvinus.ru/cr_images/userpicture/n/4080-0.png
My custom theme: https://github.com/Drsheppard01/Blenderfruit-theme

**Comment by JoshStrobl** [comment]
We are not making any considerable design changes here and with respect, it looks like ass.

**Comment by JoshStrobl** [comment]
There is already plans on redesigning the theme. You can check the issue tracker. This is for updating minor parts of the existing internal theme. There are no further design changes related to the current internal theme.

**Comment by Drsheppard01** [comment]
it looks like what i wanted. From your post:
https://twitter.com/BuddiesOfBudgie/status/1482109118383108103
Budgie-new-design

**Comment by JoshStrobl** [comment]
That is the current theme, not the planned redesign. Either way this is getting off-topic from the PR itself.

**Comment by Drsheppard01** [comment]
> That is the current theme, not the planned redesign. Either way this is getting off-topic from the PR itself.

Anyway, thanks again, sorry for the invasion

**Review by JoshStrobl — DISMISSED** [review]
Would like:

1. Screenshots of these differerences (before and after)
2. Explanation on the border changes and removal of the panel transparency handling in the workspace switcher.

**Comment by serebit** [comment]
> In reply to @JoshStrobl
1. Sure. I'll post those here after I address #2.
2. I completely forgot to handle transparent backgrounds in the workspace switcher. I'll add a commit that resolves this.

**Comment by serebit** [comment]
Screenshots below.

## This PR

Desktop w/ Raven and Budgie Menu

Polkit Dialog

## Master Branch (Plata Noir)

Desktop w/ Raven and Budgie Menu

Polkit Dialog

Run Dialog

## Before Initial Improvements (Plata Noir)

Desktop w/ Raven and Budgie Menu

Polkit Dialog

**Comment by serebit** [comment]
Updated PR description with the components that were actually modified, rather than the entire checklist.

**Review by JoshStrobl — APPROVED** [review]
LGTM, nice to see some consistency with the radiusing on the dialogs :)

**Pull request merged**
