### PR TITLE
Upstreaming budgie-trash-applet

### PR DESCRIPTION
**Pull request by EbonJaeger**
## Description
This moves my Budgie Trash Applet into the Budgie Desktop source tree.

As a part of this, the applet has been redesigned and rearchitected to better fit within Budgie Desktop:

* The header now looks similar to the in-progress Bluetooth indicator and network applet
* Buttons to restore items or empty the trash bin have been added under the header
* The concept of separate trash bins has been removed; there is just one global trash bin
* The timestamp when a file was trashed is now shown under the file's name
* Settings button has been moved to the header

In addition to the visual changes, some of the UX have been changed. The restore button no longer just restores all items in the trash; it only restores selected items. This makes it easier to restore just one file, or to quickly restore several files at once.

Also, applet settings have been changed to be per-instance, so different instances of the applet on your panels will all have their own settings, just in case you actually want that.

Lastly, upstreaming the applet more easily allows the applet to be translated into all the wonderful languages spoken by our community. Thank you, translators, for your valuable contributions! :)

Ref #28 

### Submitter Checklist

- [ ] Squashed commits with `git rebase -i` (if needed)
- [x] Built budgie-desktop and verified that the patch worked (if needed)

### CODE REVIEW

**Comment by EbonJaeger** [comment]
Speaking of translations, I entirely forgot to write that code before making the PR. Derp.

**Comment by serebit** [comment]
CI failed—you're linking against a system header for popover.h instead of the one in the source tree.

**Review by serebit — APPROVED** [review]
LGTM, thanks!

**Review by JoshStrobl — APPROVED** [review]
LGTM :rocket:

**Pull request merged**
