### PR TITLE
Update it.po

### PR DESCRIPTION
**Pull request by mki77**
## Description
Added and corrected Italian translations.

### Submitter Checklist

- [ ] Squashed commits with `git rebase -i` (if needed)
- [ ] Built budgie-desktop and verified that the patch worked (if needed)

### CODE REVIEW

**Comment by fossfreedom** [comment]
Hi - all translations are managed via transifex.  Please do join and complete the translations.  From time-to-time we pull in the latest translations - there is no need to submit via a PR.

Many thanks

https://explore.transifex.com/buddiesofbudgie/budgie-10/

**Comment by fossfreedom** [comment]
Given that the latest translations are in transifex - they may have already changed compared to what is already in github.

Thus we cannot merge the PR here because it may be behind what is already in transifex.

**Comment by JoshStrobl** [comment]
You'd have to be more specific on what specific dropdowns you are referring to.

**Comment by JoshStrobl** [comment]
No worries, thank you for raising it and I appreciate all the work you have done on the translations :heart:

**Pull request closed without merging**
